{% set name = "matrepr" %}
{% set version = "0.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/matrepr-{{ version }}.tar.gz
  sha256: e68e2b601a01ae4aab866da2062cbfd4dc1754c2bc0013d78ddf9de7bd84a48f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - tabulate

test:
  imports:
    - matrepr
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
    - html5lib
    - scipy
    - python-graphblas
    - sparse
  source_files:
    - tests/

about:
  home: https://github.com/alugowski/matrepr
  summary: Format matrices to HTML, string, and LaTeX, with Jupyter integration.
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - alugowski
