{% set name = "matrepr" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/matrepr-{{ version }}.tar.gz
  sha256: 57f5099713710e8e0dbe9573ad5561ea6e9ce251831851f115c95bfbe781eb34

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - tabulate

test:
  imports:
    - matrepr
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
    - html5lib
    - scipy
    - python-graphblas
    - sparse
  source_files:
    - tests/

about:
  home: https://github.com/alugowski/matrepr
  summary: Sparse matrix string, HTML, and LaTeX rendering with Jupyter integration.
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - alugowski
